# Generated by Django 2.2.7 on 2019-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DE', 'Denied'), ('SU', 'Successful')], default='DE', max_length=2),
        ),
    ]
