# Generated by Django 2.2.7 on 2019-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191104_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='', max_length=50)),
                ('amount', models.CharField(default='1', max_length=50)),
                ('account', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
