# Generated by Django 2.2.7 on 2019-11-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191106_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmCardNumber', models.CharField(default='', max_length=50)),
                ('accountNumber', models.CharField(default='', max_length=50)),
                ('pin', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='getsome', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(default='blah blah', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='today', max_length=50),
        ),
    ]
