# Generated by Django 2.2.6 on 2019-11-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191107_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(default='', max_length=9999999999999)),
                ('name', models.CharField(default='', max_length=9999999999999)),
                ('phoneNumber', models.CharField(default='', max_length=9999999999999)),
                ('balance', models.CharField(default='', max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='ATMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATMachineUID', models.CharField(default='', max_length=9999999999999)),
                ('currentBalance', models.CharField(default='', max_length=9999999999999)),
                ('location', models.CharField(default='', max_length=9999999999999)),
                ('minimumBalance', models.CharField(default='', max_length=9999999999999)),
                ('status', models.CharField(default='', max_length=9999999999999)),
                ('lastRefillDate', models.CharField(default='', max_length=9999999999999)),
                ('nextMaintenanceDate', models.CharField(default='', max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='ATMachineRefill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refillId', models.CharField(default='', max_length=9999999999999)),
                ('ATMachineUID', models.CharField(default='', max_length=9999999999999)),
                ('amount', models.CharField(default='', max_length=9999999999999)),
                ('atmBranch', models.CharField(default='', max_length=9999999999999)),
                ('refillDate', models.DateField(default='', max_length=9999999999999)),
                ('previousBalance', models.CharField(default='', max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceAmount', models.CharField(default='', max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaryAccountNumber', models.CharField(default='', max_length=50)),
                ('beneficiaryName', models.CharField(default='', max_length=50)),
                ('amountTransferred', models.CharField(default='', max_length=999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='CashWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountTransferred', models.CharField(default='', max_length=999999999999)),
                ('denomination', models.CharField(default='', max_length=50)),
                ('currentBalance', models.CharField(default='', max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newPhoneNumber', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PinChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousPin', models.CharField(default='', max_length=4)),
                ('newPin', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='atm_card',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm_card',
            name='cardStatus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm_card',
            name='dateOfIssue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm_card',
            name='expirationDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm_card',
            name='phoneNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm_card',
            name='twoFactorAuthenticationStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ATMachineUID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='atmCardNumber',
            field=models.CharField(default='', max_length=9999999999999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='responseCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionId',
            field=models.CharField(default='', max_length=9999999999999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='', max_length=50),
        ),
    ]
