# Generated by Django 2.2.6 on 2019-11-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191108_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountextension',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atm_card',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atmachine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atmachinerefill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountextension',
            name='accountNumber',
            field=models.CharField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atm_card',
            name='accountNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AccountExtension'),
        ),
        migrations.AlterField(
            model_name='atm_card',
            name='atmCardNumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atmachine',
            name='ATMachineUID',
            field=models.CharField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atmachinerefill',
            name='ATMachineUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ATMachine'),
        ),
        migrations.AlterField(
            model_name='atmachinerefill',
            name='refillId',
            field=models.CharField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ATMachineUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ATMachine'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='atmCardNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ATM_Card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.CharField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
    ]
