# Generated by Django 2.2.6 on 2019-11-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191112_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
    ]
