# Generated by Django 2.2.6 on 2019-11-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191112_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
