# Generated by Django 2.2.6 on 2019-11-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191112_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, default=' ', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='', max_length=16),
        ),
    ]
