# Generated by Django 2.2.6 on 2019-11-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191112_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accountNumber',
        ),
    ]
